### ISSUE TITLE
Support Lets-Encrypt for DNS records that return multipe IPs

### ISSUE THREAD

**Issue by cyberjunk** [sfproductlabs/tracker#11]
### Consider the following DNS configuration:

**Hosts:**
tr1.company.com [IP:A]
tr2.company.com [IP:B]
tr3.company.com [IP:C]

**Load-Balanced/Failsafe Endpoint for Clients:**
tr.company.com [IP:A,B,C]

### Problem:

The builtin Lets-Encrypt support fails when trying to use 'tr.company.com' in the tracker, e.g. in config of tr1, tr2 and tr3:

>> "Domains": [
        "tr.company.com"
    ]

Because Lets-Encrypt tries to validate the challenge on an arbitrary IP returned from DNS (A, B or C) and not necessarily the one that is waiting for it (e.g. A).

A similar problem is also described here: 
https://community.letsencrypt.org/t/a-record-with-multiple-ips/72035

It kinda suggests to specify a "Lets-Encrypt-Master" and have every other instance use a 301 foward to this "Master" for the challenge. This should work to receive the cert+key successfully on this 'Master', but the cert+key would still need to be shared with other instances...

May be you got a cool idea how to support this ?

**Comment by dioptre** [comment]
Oo interesting suggestion mate, for behind loadbalancers/firewalls you can use a certificate for now. Let me think about this as is normally handled in production on AWS with their certificate manager and load balancer.

**Comment by cyberjunk** [comment]
**Regarding:**

>> for behind loadbalancers/firewalls you can use a certificate for now

**For AWS:** 
Yes, they provide a certificate for the external side of the LB and the tracker can easily run with a self-signed one internally.

**For Scaleway (probably other cheap providers):** 
No, for HTTPS their LB is a simple TCP pass-through. Each endpoint is still expected to provide the proper certificate on its own. See this info on their site:

![scaleway_lb](https://user-images.githubusercontent.com/780159/65671223-25069900-e047-11e9-85ef-72f71137f2a9.PNG)

Also their LB is super limited (single ip, not scaling, no ipv6, no ....) so it doesn't seem any better than simply running a DNS based load-balancing/fail-safe (like mentioned setup), which is also probably very common setup for non AWS accounts...

**Comment by dioptre** [comment]
Geez a http pass through is garbage hey...

Let's look at https://traefik.io/

**Comment by dioptre** [comment]
Made this to support it
https://github.com/sfproductlabs/roo
