### ISSUE TITLE
Support Certificate Per Domain

### ISSUE THREAD

**Issue by cyberjunk** [sfproductlabs/tracker#12]
This is related to multi-site/multi-customer tracking (not sure how you called it exactly).
Consider a tracker hosted by some 'companyA' for an internal 'project1' and different customers with domains in config set like (without any Load-Balancer providing certificates):

>> "Domains": [
        "tr.companyA.com",
        "tr.project1.companyA.com",
        "tr.customer1.com"
        "tr.customer2.com"
    ],

But currently you can only specify a single certificate (if provided manually):

>>    "TLSCert" : "./.setup/keys/example/server.crt",
    "TLSKey" : "./.setup/keys/example/server.key",

AFAIK such a setup would require a certificate that lists all domains mentioned in the config in the SAN of the certificate. For builtin Lets-Encrypt that is no problem, supported and probably the way to go. But for manual certificates (e.g. existing one provided by a new customer) this could become a problem, same when 'companyA' tries to maintain one professional/bought one for all customers (has to update/change the SAN all the time).

If possible, please consider changing it so that one optionally can provide a certificate per domain/site (like you can do in nginx too)...

**Comment by dioptre** [comment]
Have you tried putting more than one key/cert in those files?

**Comment by dioptre** [comment]
Perhaps I need to do https://grokbase.com/t/gg/golang-nuts/136449jr5g/go-nuts-sni-server-name-indication-support-for-listenandservetls

**Comment by dioptre** [comment]
Might also be better to set up a LB in AWS too mate....

**Comment by cyberjunk** [comment]
>> Have you tried putting more than one key/cert in those files?

No, not yet. Should I ?

>> Perhaps I need to do https://grokbase.com/t/gg/golang-nuts/136449jr5g/go-nuts-sni-server-name-indication-support-for-listenandservetls

Yes, I think SNI is the keyword here. I think this is what should allow a server to select and present a certificate from many based on the client-requested hostname.

>> Might also be better to set up a LB in AWS too mate....

Aww, may be not everyone is on AWS? ;-)
I think if you want a true multi customer/sites enabled tracker, you should try to look into this...

For LetsEncrypt the curent single certificate with many SAN on it is really the way to go. But especially for bought certificates this isn't really true, I'm afraid. Adding a SAN to a single certificate whenever you got a new customer might turn out very unhandy or is kinda impossible without paying again for the cert (at least for cheaper ones).

**Comment by dioptre** [comment]
I think this is the role for the LB mate.

Check out https://traefik.io/ and let's chat.

**Comment by dioptre** [comment]
Made this to support it
https://github.com/sfproductlabs/roo
